spring.datasource.url=jdbc:postgresql://localhost:5432/book_social_network
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=jupiter
spring.mail.password=jupiter
spring.mail.properties.mail.smtp.trust=*
spring.mail.properties.mail.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.connectiontimeout=5000
spring.mail.properties.mail.timeout=3000
spring.mail.properties.mail.writetimeout=5000

application.security.jwt.secret=8c74e7c5beecd0bc62a93c2b145bb065919832fd762c3f6a8cc4b79be92d00ed
application.security.jwt.expiration=8640000