/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  authorName: string;
  id?: number;
  isbn: string;
  shareable?: boolean;
  synopsys: string;
  title: string;
}
